<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260423080348 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE club (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, short_name VARCHAR(255) NOT NULL, code VARCHAR(3) NOT NULL, badge_url VARCHAR(255) DEFAULT NULL, stadium_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B8EE38727E860E36 ON club (stadium_id)');
        $this->addSql('CREATE TABLE competition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, logo_url VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE fixture (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, home_score SMALLINT DEFAULT NULL, away_score SMALLINT DEFAULT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(255) DEFAULT \'SCHEDULED\' NOT NULL, home_team_id INT DEFAULT NULL, away_team_id INT DEFAULT NULL, stadium_id INT DEFAULT NULL, competition_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5E540EE9C4C13F6 ON fixture (home_team_id)');
        $this->addSql('CREATE INDEX IDX_5E540EE45185D02 ON fixture (away_team_id)');
        $this->addSql('CREATE INDEX IDX_5E540EE7E860E36 ON fixture (stadium_id)');
        $this->addSql('CREATE INDEX IDX_5E540EE7B39D312 ON fixture (competition_id)');
        $this->addSql('CREATE TABLE stadium (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, country VARCHAR(255) NOT NULL, city VARCHAR(255) NOT NULL, capacity INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E604044F5E237E06 ON stadium (name)');
        $this->addSql('ALTER TABLE club ADD CONSTRAINT FK_B8EE38727E860E36 FOREIGN KEY (stadium_id) REFERENCES stadium (id)');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT FK_5E540EE9C4C13F6 FOREIGN KEY (home_team_id) REFERENCES club (id)');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT FK_5E540EE45185D02 FOREIGN KEY (away_team_id) REFERENCES club (id)');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT FK_5E540EE7E860E36 FOREIGN KEY (stadium_id) REFERENCES stadium (id)');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT FK_5E540EE7B39D312 FOREIGN KEY (competition_id) REFERENCES competition (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE club DROP CONSTRAINT FK_B8EE38727E860E36');
        $this->addSql('ALTER TABLE fixture DROP CONSTRAINT FK_5E540EE9C4C13F6');
        $this->addSql('ALTER TABLE fixture DROP CONSTRAINT FK_5E540EE45185D02');
        $this->addSql('ALTER TABLE fixture DROP CONSTRAINT FK_5E540EE7E860E36');
        $this->addSql('ALTER TABLE fixture DROP CONSTRAINT FK_5E540EE7B39D312');
        $this->addSql('DROP TABLE club');
        $this->addSql('DROP TABLE competition');
        $this->addSql('DROP TABLE fixture');
        $this->addSql('DROP TABLE stadium');
    }
}
